//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_MANIFEST : DbContext
    {
        public DB_MANIFEST()
            : base("name=DB_MANIFEST")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADU_ADUANAAGENT> TBL_ADU_ADUANAAGENT { get; set; }
        public virtual DbSet<TBL_ADU_ADUANADESTINATION> TBL_ADU_ADUANADESTINATION { get; set; }
        public virtual DbSet<TBL_ADU_MANIFEST> TBL_ADU_MANIFEST { get; set; }
        public virtual DbSet<TBL_ADU_MANIFESTSHIPMENTDETAILDOC> TBL_ADU_MANIFESTSHIPMENTDETAILDOC { get; set; }
        public virtual DbSet<TBL_ADU_MANIFESTSHIPMENTDOC> TBL_ADU_MANIFESTSHIPMENTDOC { get; set; }
        public virtual DbSet<TBL_ADU_MASTERINFORMATION> TBL_ADU_MASTERINFORMATION { get; set; }
        public virtual DbSet<TBL_ADU_TRACK> TBL_ADU_TRACK { get; set; }
        public virtual DbSet<TBL_ADU_WAREDESCRIPTION> TBL_ADU_WAREDESCRIPTION { get; set; }
        public virtual DbSet<TBL_ADU_WEBTRACKING> TBL_ADU_WEBTRACKING { get; set; }
        public virtual DbSet<TBL_MAN_MANIFEST> TBL_MAN_MANIFEST { get; set; }
    
        public virtual ObjectResult<TBL_MAN_MANIFEST> InsertAndGetManifests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_MAN_MANIFEST>("InsertAndGetManifests");
        }
    
        public virtual ObjectResult<TBL_MAN_MANIFEST> InsertAndGetManifests(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_MAN_MANIFEST>("InsertAndGetManifests", mergeOption);
        }
    }
}
