//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_ADUANADESTINATION
    {
        public decimal NUM_ADUANADESTINATIONID { get; set; }
        public string VCH_MANIFEST { get; set; }
        public Nullable<int> INT_SEC { get; set; }
        public string VCH_DUANUMBER { get; set; }
        public string VCH_DATENUMBERING { get; set; }
        public Nullable<int> INT_DETAIL { get; set; }
        public string VCH_AGENT { get; set; }
        public Nullable<decimal> NUM_WEIGHTREQUESTED { get; set; }
        public Nullable<int> INT_PACKAGEREQUESTED { get; set; }
        public string VCH_DATEDATED { get; set; }
        public Nullable<decimal> DEC_MANIFESTSHIPDETDOCID { get; set; }
    }
}
