//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_FLIGHT
    {
        public int INT_FREIGHTDESTINATION { get; set; }
        public Nullable<decimal> DEC_MANIFESTSHIPDETDOCID { get; set; }
        public string VCH_ORIGIN { get; set; }
        public string VCH_DESTINATION { get; set; }
        public string VCH_CONNECTION { get; set; }
    }
}
