//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_WAREDESCRIPTION
    {
        public decimal DEC_WAREDESCRIPTION { get; set; }
        public string VCH_MANIFEST { get; set; }
        public Nullable<decimal> DEC_PACKAGES { get; set; }
        public Nullable<decimal> DEC_GROSSWEIGHT { get; set; }
        public string VCH_PACKING { get; set; }
        public string VCH_CONSIGNEE { get; set; }
        public string VCH_MARKSANDNUMBERS { get; set; }
        public string VCH_DESCRIPTION { get; set; }
        public Nullable<decimal> DEC_MANIFESTSHIPDETDOCID { get; set; }
        public string VCH_SHIPPER { get; set; }
    }
}
