//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_MANIFESTSHIPMENTDOC
    {
        public decimal NUM_MANIFESTSHIPMENTDOCID { get; set; }
        public Nullable<decimal> NUM_MANIFESTID { get; set; }
        public string VCH_MANIFESTNUMBER { get; set; }
        public Nullable<int> INT_DETAILSNUMBER { get; set; }
        public string DAT_DEPARTUREDATE { get; set; }
        public Nullable<decimal> DEC_GROSSWEIGHT { get; set; }
        public string VCH_AIRLINE { get; set; }
        public string VCH_NATIONALITY { get; set; }
        public string VCH_FLIGHTNUMBER { get; set; }
        public Nullable<int> INT_PACKAGES { get; set; }
        public string VCH_FINALDATEBOARD { get; set; }
        public string VCH_DATEAUTHORIZATIONBOARD { get; set; }
        public string VCH_MANIFESTTRANSMISSIONDATE { get; set; }
    }
}
