//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SLI_CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SLI_CITY()
        {
            this.TBL_SLI_PROVINCE = new HashSet<TBL_SLI_PROVINCE>();
        }
    
        public int INT_CITYID { get; set; }
        public string VCH_NAME { get; set; }
        public Nullable<bool> BIT_STATE { get; set; }
        public int INT_COUNTRYID { get; set; }
        public string VCH_INTCODE { get; set; }
        public string VCH_IATACODE { get; set; }
    
        public virtual TBL_SLI_COUNTRY TBL_SLI_COUNTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SLI_PROVINCE> TBL_SLI_PROVINCE { get; set; }
    }
}
