//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SLI_PROVINCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SLI_PROVINCE()
        {
            this.TBL_SLI_DISTRICT = new HashSet<TBL_SLI_DISTRICT>();
        }
    
        public int INT_PROVINCEID { get; set; }
        public string VCH_NAME { get; set; }
        public Nullable<bool> BIT_STATE { get; set; }
        public Nullable<int> INT_CITYID { get; set; }
    
        public virtual TBL_SLI_CITY TBL_SLI_CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SLI_DISTRICT> TBL_SLI_DISTRICT { get; set; }
    }
}
