//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SLI_CURRENCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SLI_CURRENCY()
        {
            this.TBL_SLI_COUNTRY = new HashSet<TBL_SLI_COUNTRY>();
        }
    
        public int INT_CURRENCYID { get; set; }
        public string CHR_ADUANACODE { get; set; }
        public string VCH_NAME { get; set; }
        public Nullable<bool> BIT_ACTIVE { get; set; }
        public string VCH_SYMBOL { get; set; }
        public string VCH_CURRENCYSYMBOL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SLI_COUNTRY> TBL_SLI_COUNTRY { get; set; }
    }
}
