//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_MASTERINFORMATION
    {
        public decimal DEC_MASTERINFORMATIONID { get; set; }
        public string VCH_MANIFEST { get; set; }
        public Nullable<int> INT_DETAILNUMBER { get; set; }
        public string VCH_TERMINALCODE { get; set; }
        public string VCH_SHIPMENTPORT { get; set; }
        public Nullable<decimal> DEC_WEIGHTORIGIN { get; set; }
        public Nullable<decimal> DEC_PACKAGEORIGIN { get; set; }
        public Nullable<decimal> DEC_WEIGHTRECEIVED { get; set; }
        public Nullable<decimal> DEC_PACKAGERECEIVED { get; set; }
        public string VCH_CONSIGNEE { get; set; }
        public string VCH_DESTINATIONPORT { get; set; }
        public string VCH_TRANSMISSIONDATE { get; set; }
        public Nullable<decimal> DEC_MANIFESTSHIPDETDOCID { get; set; }
        public string VCH_SHIPPER { get; set; }
        public Nullable<decimal> DEC_MANIFESTEDWEIGHT { get; set; }
        public Nullable<decimal> DEC_MANIFESTEDPACKAGE { get; set; }
    }
}
