//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SLI_COUNTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SLI_COUNTRY()
        {
            this.TBL_SLI_CITY = new HashSet<TBL_SLI_CITY>();
        }
    
        public int INT_COUNTRYID { get; set; }
        public string VCH_FREIGHTCODE { get; set; }
        public string VCH_NAME { get; set; }
        public Nullable<bool> BIT_STATE { get; set; }
        public Nullable<int> INT_CURRENCYID { get; set; }
        public Nullable<int> INT_CONTINENTID { get; set; }
        public Nullable<bool> BIT_SPANISHLANGUAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SLI_CITY> TBL_SLI_CITY { get; set; }
        public virtual TBL_SLI_CONTINENT TBL_SLI_CONTINENT { get; set; }
        public virtual TBL_SLI_CURRENCY TBL_SLI_CURRENCY { get; set; }
    }
}
