//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_ADUANAAGENT
    {
        public int INT_ADUANAAGENTID { get; set; }
        public string VCH_SUNATCODE { get; set; }
        public string VCH_BUSINESSNAME { get; set; }
        public string VCH_SUNATJURISDICTIONCODE { get; set; }
        public string VCH_JURISDICTION { get; set; }
        public string VCH_STATE { get; set; }
    }
}
