//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADU_TRACK
    {
        public int INT_TRACKID { get; set; }
        public Nullable<decimal> NUM_MANIFESTSHIPDETDOCID { get; set; }
        public string VCH_DIRECTMASTERGUIDE { get; set; }
        public string VCH_ORIGIN { get; set; }
        public string VCH_DESTINATION { get; set; }
        public string VCH_CONNECTION { get; set; }
        public Nullable<int> INT_PIECES { get; set; }
        public Nullable<decimal> NUM_WEIGHT { get; set; }
        public Nullable<decimal> NUM_VOLUME { get; set; }
        public string VCH_PRODUCT { get; set; }
        public string VCH_STATUS { get; set; }
        public string VCH_CONFIRMATION { get; set; }
        public string VCH_SERVICE { get; set; }
    }
}
